# source files in this project (main.* is automatically assumed)
SOURCES := worse.asm

# header files in this project
HEADERS :=

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ../../hwlib/demo/arduino-due
include $(RELATIVE)/makefile.link